### ISSUE TITLE
Layout is broken after rotation

### ISSUE THREAD

**Issue by gerchicov-bp** [hemangshah/Feelings#1]

**Comment by hemangshah** [comment]
@gerchicov-bp, sorry for the late reply, but right now, I am getting this error when compiling (or even open the project) in both Xcode 9 and Xcode 8.3 versions.

"Use of unresolved identifier '**FeelingsView**'".

I am not sure what is wrong with my code here? Are you getting the same error? Or how you're checking it at your end? Any help would be appreciated.

**Update**: I have also fixed this by change the source folder name to something different that then source file name.

**Comment by hemangshah** [comment]
@gerchicov-bp, I simply set `autoresizingMask`s and that fixed this issue.

`viewFeeling.autoresizingMask = [.flexibleLeftMargin, .flexibleRightMargin, .flexibleTopMargin, .flexibleBottomMargin]`

I will commit the updated code soon thank you for your time to check this repo and provided me this issue. 👍
